### ISSUE TITLE
Feature Request change info

### ISSUE THREAD

**Issue by dathacky** [EomTaeWook/DiademMacro#14]
Please update to add change info feature. Thanks a lot

<img width="782" alt="Screenshot 2024-05-25 at 12 06 14" src="https://github.com/EomTaeWook/AppPlayerMacro/assets/37299929/5d7bdb58-6149-454a-ac8e-a24f21147eee">

**Comment by EomTaeWook** [comment]
The information you provided appears to set properties on a device, likely for Android OS (AOS) or iOS. These properties, such as IMEI, IMSI, manufacturer, and model, are typically used for device configuration or testing purposes in mobile operating systems.

Since your macro program is intended to operate on Windows OS, these specific properties do not seem directly relevant. Windows OS does not typically require or use mobile-specific properties like IMEI or IMSI.

Could you please provide more context or clarify how you intend to use these properties within your Windows-based macro program? This additional information will help determine if there is a way to adapt or translate these settings for your intended use.

**Comment by dathacky** [comment]
The above commands are from ldplayer, I want to use it to change the `IMEI, IMSI, manufacturer, and model` information as you said, you can set up the feature to randomly change the above parameters on startup ldplayer? Thank

**Comment by EomTaeWook** [comment]
By visiting the following 

GitHub repository: https://github.com/drnxloc/AutoLDPlayer

you can find the source code to modify the settings of LDPlayer. This seems like a good solution to resolve the issue.

My macro is intended for general-purpose programs. A program that is only applicable to specific software does not fit the concept.
